### PR TITLE
Updated Windows build environment

### PR DESCRIPTION
**Pull request by simonowen**
- replaced VS project with Open Folder style
- fixed missing DLL exports on CMake build
- generate version resource from template
- exposed version numbers via config.h
- updated .gitignore for generated files
- removed unused automake files

### CODE REVIEW

**Comment by simonowen** [comment]
How attached are you to the Visual Studio project files?

I started this commit as a fix for built DLLs having no exports (since the project needs a .def file rather than using __declspec(dllexport) to export them).  As part of the refactor to pull in the .def file when needed I've also templated the version number in the .rc file.  Since that'd no longer be editible from VS I've removed the project files -- you can get the same output files without them.

You can now use Open Folder from VS2017 or later and it'll pick up the CMakeFile.txt.  You can add Release configurations from the Manage Configurations dropdown. Use the "install SAASound" option from the Build menu to copy to out/instal/ under the project directory.  I've tested the built DLL with SimCoupe v1.0.  I've also prepared a vcpkg package for the library that can pull the source from your GitHub page.

If this is too radical I can separate the underlying fix and leave the existing project files.  :)

**Comment by simonowen** [comment]
I'll maintain a fork with these changes.

**Comment by stripwax** [comment]
Oh hi!  Sorry I totally didn't read this thread..   What exactly was the
problem with missing exports / what was the fix?  Actually I included the
SAASound.exp in the release package too, and it gets built by the VS
build.  I'm not using CMake (but I could, and it looks like that would
integrate nicely with a github pipeline too.)

**Comment by simonowen** [comment]
I'd forgotten about it too, and only spotted it when I went to check if there were any other updates I'd missed.

The fix was that the DLL built by the CMake build system had no functions exported from the DLL, so it didn't actually work. Using  `dumpbin /exports saasound.dll` should show a list of functions, but they were missing because it wasn't using the .def file.

The other changes were to move the rest of building exclusively to CMake, which made it easy for me to build it for any platform, without having to mirror changes made to the Windows-only project+solution files. The changes also made it compatible with the vcpkg system, which is a bit like apt-get under Windows, and something Visual Studio can use to find library dependencies. Ultimately it made it much easier for me to use the external SAASound with SimCoupe.

I'll separate out the export fix from the other changes, so you can have one without the other.

**Pull request closed without merging**
